image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git
    - JSonSchema

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - chmod +x driver/lin/chromedriver
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации